
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GE = 41;
  public static final int UMINUS = 5;
  public static final int BVAL = 25;
  public static final int SLPAR = 47;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int INT = 22;
  public static final int MINUS = 4;
  public static final int FLOOR = 28;
  public static final int RPAREN = 8;
  public static final int SEMICOLON = 50;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int LT = 38;
  public static final int RPAR = 44;
  public static final int FUN = 11;
  public static final int OR = 35;
  public static final int COMMA = 51;
  public static final int BOOL = 24;
  public static final int DIV = 33;
  public static final int BEGIN = 20;
  public static final int PLUS = 3;
  public static final int ASSIGN = 42;
  public static final int IF = 13;
  public static final int ID = 52;
  public static final int LE = 40;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 37;
  public static final int CLPAR = 45;
  public static final int SIZE = 26;
  public static final int error = 1;
  public static final int MUL = 32;
  public static final int ADD = 30;
  public static final int NUMBER = 9;
  public static final int SRPAR = 48;
  public static final int REAL = 23;
  public static final int TIMES = 6;
  public static final int RVAL = 54;
  public static final int COLON = 49;
  public static final int ELSE = 15;
  public static final int READ = 18;
  public static final int WHILE = 16;
  public static final int FLOAT = 27;
  public static final int THEN = 14;
  public static final int END = 21;
  public static final int LPAR = 43;
  public static final int CEIL = 29;
  public static final int GT = 39;
  public static final int SUB = 31;
  public static final int VAR = 10;
  public static final int PRINT = 19;
  public static final int DO = 17;
  public static final int CRPAR = 46;
  public static final int IVAL = 53;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "VAR",
  "FUN",
  "RETURN",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "READ",
  "PRINT",
  "BEGIN",
  "END",
  "INT",
  "REAL",
  "BOOL",
  "BVAL",
  "SIZE",
  "FLOAT",
  "FLOOR",
  "CEIL",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "AND",
  "OR",
  "NOT",
  "EQUAL",
  "LT",
  "GT",
  "LE",
  "GE",
  "ASSIGN",
  "LPAR",
  "RPAR",
  "CLPAR",
  "CRPAR",
  "SLPAR",
  "SRPAR",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "ID",
  "IVAL",
  "RVAL"
  };
}

